image:
  repository: referral-orchestration-service
port: 8091
replicas: 1
hpa:
  enabled: false
pdb:
  enabled: false
env:
  SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "3"
  SERVER_PORT: "8091"
envFrom:
  - referral-redis
  - referral-db
  - referral-jwt
